import React from 'react';
import { SignalBadge } from './SignalBadge';
import { ConfidenceBar } from './ConfidenceBar';
import { Zap, Globe, MessageSquare, Brain } from 'lucide-react';

interface AgentCardProps {
  agentName: string;
  signal: string;
  confidence?: number;
  reasons?: string[];
}

export function AgentCard({ agentName, signal, confidence, reasons = [] }: AgentCardProps) {
  const normVal = confidence !== undefined ? (confidence < 1 ? confidence * 100 : confidence) : undefined;
  
  // Icon select
  const getAgentIcon = (name: string) => {
    const lower = name.toLowerCase();
    if (lower.includes('tech')) return <Zap size={16} className="text-amber-400" />;
    if (lower.includes('macro')) return <Globe size={16} className="text-sky-400" />;
    if (lower.includes('sent')) return <MessageSquare size={16} className="text-emerald-400" />;
    return <Brain size={16} className="text-violet-400" />;
  };

  return (
    <div id={`agent-card-${agentName.replace(/\s+/g, '-').toLowerCase()}`} className="bg-slate-800 border border-slate-700/60 rounded-xl p-5 shadow-lg flex flex-col justify-between hover:border-slate-600 transition-all duration-300">
      <div>
        <div className="flex justify-between items-start mb-3">
          <div className="flex items-center gap-2">
            <span className="p-1.5 bg-slate-900 rounded-lg border border-slate-700/40 shrink-0">
              {getAgentIcon(agentName)}
            </span>
            <h5 className="font-bold text-white text-sm font-sans tracking-tight">{agentName}</h5>
          </div>
          <SignalBadge signal={signal} size="sm" />
        </div>

        {reasons && reasons.length > 0 ? (
          <ul className="space-y-1.5 mt-3 mb-4">
            {reasons.map((r, i) => (
              <li key={i} className="text-[11px] text-slate-400 leading-normal flex items-start gap-1.5">
                <span className="text-slate-600 font-mono mt-0.5">•</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-[11px] text-slate-500 italic mt-3 mb-4">No specific reasons generated by agent.</p>
        )}
      </div>

      {normVal !== undefined && (
        <div className="mt-auto pt-2 border-t border-slate-700/30">
          <ConfidenceBar confidence={normVal} label="Agent Reliability" />
        </div>
      )}
    </div>
  );
}
