from sqlalchemy import create_all, create_engine, Column, Integer, String, Float, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import datetime
import os

Base = declarative_base()

class Price(Base):
    """
    Stores historical price data for all tracked assets.
    """
    __tablename__ = 'prices'
    id = Column(Integer, primary_key=True)
    symbol = Column(String(50), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Integer)
    interval = Column(String(10))

class Prediction(Base):
    """
    Stores predictions generated by the ensemble orchestrator.
    """
    __tablename__ = 'predictions'
    id = Column(Integer, primary_key=True)
    symbol = Column(String(50), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    signal = Column(String(20)) # Up, Down, Sideways
    confidence = Column(Float)
    technical_signal = Column(String(50))
    macro_signal = Column(String(50))
    ml_signal = Column(String(50))
    sentiment_signal = Column(String(50))
    reasons = Column(Text)
    timeframe = Column(String(20))

class AccuracyLog(Base):
    """
    Tracks prediction performance for self-learning.
    """
    __tablename__ = 'accuracy_logs'
    id = Column(Integer, primary_key=True)
    prediction_id = Column(Integer, ForeignKey('predictions.id'))
    symbol = Column(String(50))
    predicted = Column(String(20))
    actual = Column(String(20))
    was_correct = Column(Boolean)
    checked_at = Column(DateTime, default=datetime.datetime.utcnow)

class NewsCache(Base):
    """
    Caches processed news for sentiment analysis.
    """
    __tablename__ = 'news_cache'
    id = Column(Integer, primary_key=True)
    symbol = Column(String(50), index=True)
    headline = Column(Text)
    url = Column(String(255))
    published_at = Column(DateTime)
    sentiment_score = Column(Float)
    sentiment_label = Column(String(20))
    processed_at = Column(DateTime, default=datetime.datetime.utcnow)

def init_db(db_url="sqlite:///data/predictions.db"):
    """
    Initializes the database and creates all tables.
    """
    # Ensure directory exists
    db_dir = os.path.dirname(db_url.replace("sqlite:///", ""))
    if db_dir and not os.path.exists(db_dir):
        os.makedirs(db_dir)
        
    engine = create_engine(db_url)
    Base.metadata.create_all(engine)
    print(f"Database initialized at {db_url}")
    return engine

def get_session(db_url="sqlite:///data/predictions.db"):
    """
    Returns a new database session.
    """
    engine = create_engine(db_url)
    Session = sessionmaker(bind=engine)
    return Session()
